name: Web App Scanning (DAST)

on: [push]

jobs:
  scan-pr-attempt:
    runs-on: ubuntu-latest
    name: API-Security-Scanner
    services:
      movies:
        image: ghcr.io/dvdmelamed/goat-movies
        options: >-
          --health-cmd="curl http://127.0.0.1:80/movies/count || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 8089:80
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          format: openapi
          target: 'http://127.0.0.1:8089/openapi.json'
          fail_action: true
