name: Dependency Check (SCA)

on: [push]

# Declare default permissions as read only.
permissions: read-all

jobs:
  scan-pr-attempt:
    uses: "another-rex/osv-scanner/.github/workflows/osv-scanner-reusable-pr.yml@attempt-at-multiline-action"