name: Dependency Check (SCA)

on: [push]

# Declare default permissions as read only.
permissions: read-all

jobs:
  scan-pr-attempt:
    name: "Run scanner on new code"
    uses: google/osv-scanner/actions/scanner@main
    with:
      results-format: json
      results-file: new-results.json
      to-scan: .
    continue-on-error: true