name: Secret Detection

on: [push]

jobs:
  scan-pr-attempt:
    runs-on: ubuntu-latest
    name: Secret-Scanner
    steps:
      - uses: actions/checkout@v1
      - name: Secret Detection
        uses: zricethezav/gitleaks-action@master